#!/bin/bash
# Author: Arthur Brinkmann
# Date: 02/28/2023
# Description: This script will pull only Error messages from /var/log/syslog
# Modified: 02/28/2023

grep -i error /home/arthurbrinkmann/dev/CompleteLinuxBashShellCourse/professional-scripts/syslog > /home/arthurbrinkmann/dev/CompleteLinuxBashShellCourse/professional-scripts/output-error 
